import type { TenantCacheDomain } from "./tenant-cache-domains";
import type { TenantMutationReason } from "./tenant-mutation-reasons";

const SALES_FINANCE_DOMAINS: TenantCacheDomain[] = [
  "sales",
  "sale-detail",
  "dashboard",
  "products",
  "product-detail",
  "warehouse-stock",
  "stock-movements",
  "customers",
  "customer-detail",
  "customer-ledger",
  "cash-bank",
  "reports",
  "notifications",
];

const STOCK_DOMAINS: TenantCacheDomain[] = [
  "products",
  "product-detail",
  "warehouse-stock",
  "stock-movements",
  "dashboard",
  "reports",
];

const CASH_DOMAINS: TenantCacheDomain[] = [
  "cash-bank",
  "dashboard",
  "reports",
  "notifications",
];

const SUPPLIER_FINANCE_DOMAINS: TenantCacheDomain[] = [
  "suppliers",
  "supplier-detail",
  "supplier-ledger",
  "cash-bank",
  "expenses",
  "dashboard",
  "reports",
];

const EMPLOYEE_FINANCE_DOMAINS: TenantCacheDomain[] = [
  "employees",
  "employee-detail",
  "cash-bank",
  "expenses",
  "dashboard",
  "reports",
];

/** Mutation → etkilenen cache domain'leri. Finans/stok için geniş; metadata toggle dar. */
export const TENANT_MUTATION_INVALIDATION: Record<
  TenantMutationReason,
  readonly TenantCacheDomain[]
> = {
  "sale-create": SALES_FINANCE_DOMAINS,
  "sale-update": SALES_FINANCE_DOMAINS,
  "sale-cancel": SALES_FINANCE_DOMAINS,
  "sale-return": SALES_FINANCE_DOMAINS,
  "sale-collect": [
    "sales",
    "sale-detail",
    "customers",
    "customer-detail",
    "customer-ledger",
    "cash-bank",
    "dashboard",
    "reports",
    "notifications",
  ],
  "pos-checkout": SALES_FINANCE_DOMAINS,
  "stock-movement": STOCK_DOMAINS,
  "stock-count": STOCK_DOMAINS,
  "warehouse-transfer": [...STOCK_DOMAINS, "notifications"],
  "warehouse-transfer-cancel": [...STOCK_DOMAINS, "notifications"],
  "product-create": STOCK_DOMAINS,
  "product-update": STOCK_DOMAINS,
  "customer-create": ["customers", "dashboard", "reports"],
  "customer-update": ["customers", "customer-detail", "customer-ledger", "dashboard"],
  "customer-collect": [
    "customers",
    "customer-detail",
    "customer-ledger",
    "cash-bank",
    "dashboard",
    "reports",
    "notifications",
  ],
  "customer-payment": [
    "customers",
    "customer-detail",
    "customer-ledger",
    "cash-bank",
    "dashboard",
    "reports",
    "notifications",
  ],
  "supplier-create": ["suppliers", "dashboard", "reports"],
  "supplier-update": ["suppliers", "supplier-detail", "supplier-ledger", "dashboard"],
  "supplier-payment": SUPPLIER_FINANCE_DOMAINS,
  "supplier-collect": SUPPLIER_FINANCE_DOMAINS,
  "supplier-adjustment": SUPPLIER_FINANCE_DOMAINS,
  "employee-payment": EMPLOYEE_FINANCE_DOMAINS,
  "employee-salary": EMPLOYEE_FINANCE_DOMAINS,
  "employee-status": ["employees", "employee-detail", "dashboard"],
  "expense-create": ["expenses", "cash-bank", "dashboard", "reports", "notifications"],
  "expense-cancel": ["expenses", "cash-bank", "dashboard", "reports"],
  "expense-pay": ["expenses", "cash-bank", "dashboard", "reports", "notifications"],
  "cash-bank-manual-transaction": CASH_DOMAINS,
  "cash-daily-close": CASH_DOMAINS,
  "account-transfer": CASH_DOMAINS,
  "account-create": CASH_DOMAINS,
  "invoice-create": [
    "invoices",
    "invoice-detail",
    "sales",
    "sale-detail",
    "customers",
    "customer-detail",
    "customer-ledger",
    "cash-bank",
    "dashboard",
    "reports",
    "notifications",
  ],
  "invoice-update": ["invoices", "invoice-detail"],
  "invoice-cancel": [
    "invoices",
    "invoice-detail",
    "sales",
    "sale-detail",
    "customers",
    "customer-detail",
    "customer-ledger",
    "dashboard",
    "reports",
  ],
  "invoice-delete": ["invoices", "dashboard"],
  "invoice-collect": [
    "invoices",
    "invoice-detail",
    "sales",
    "sale-detail",
    "customers",
    "customer-detail",
    "customer-ledger",
    "cash-bank",
    "dashboard",
    "reports",
    "notifications",
  ],
  "invoice-status-change": ["invoices", "invoice-detail"],
  "invoice-bulk-action": ["invoices", "invoice-detail", "dashboard"],
  "invoice-create-from-sale": [
    "invoices",
    "invoice-detail",
    "sales",
    "sale-detail",
    "dashboard",
    "reports",
    "notifications",
  ],
  "e-invoice-create": [
    "invoices",
    "invoice-detail",
    "sales",
    "sale-detail",
    "customers",
    "customer-detail",
    "customer-ledger",
    "dashboard",
    "reports",
  ],
  "invoice-e-document-action": ["invoices", "invoice-detail", "notifications"],
  "notification-read": ["notifications", "dashboard"],
  "metadata-toggle": [],
  // ─── Sipariş modülü ───────────────────────────────────────────────────────
  "order-status-update": ["orders", "order-detail", "dashboard"],
  "order-approve": [
    "orders",
    "order-detail",
    "products",
    "product-detail",
    "warehouse-stock",
    "stock-movements",
    "dashboard",
  ],
  "order-cancel": ["orders", "order-detail", "dashboard"],
  "order-archive": ["orders", "order-detail", "dashboard"],
  "order-restore": ["orders", "order-detail", "dashboard"],
  "order-bulk-status": ["orders", "order-detail", "dashboard"],
  "order-bulk-shipping": ["orders", "order-detail", "dashboard"],
  "order-import": [
    "orders",
    "order-detail",
    "products",
    "warehouse-stock",
    "dashboard",
  ],
  // ─── Teklif modülü ────────────────────────────────────────────────────────
  "quote-cancel": ["quotes", "sales", "sale-detail", "dashboard"],
  "quote-convert": [
    "quotes",
    "sales",
    "sale-detail",
    "products",
    "product-detail",
    "warehouse-stock",
    "stock-movements",
    "customers",
    "customer-detail",
    "customer-ledger",
    "cash-bank",
    "dashboard",
    "reports",
  ],
  // ─── Metadata yöneticileri ────────────────────────────────────────────────
  "product-category-change": ["products", "product-detail"],
  "expense-category-change": ["expenses"],
  "customer-group-change": ["customers", "customer-detail", "customer-ledger"],
};

export function getDomainsForMutation(
  reason: TenantMutationReason,
): readonly TenantCacheDomain[] {
  return TENANT_MUTATION_INVALIDATION[reason];
}
