/** Mutation sonrası invalidation matrisi anahtarları. */
export const TENANT_MUTATION_REASONS = [
  "sale-create",
  "sale-update",
  "sale-cancel",
  "sale-collect",
  "pos-checkout",
  "stock-movement",
  "stock-count",
  "warehouse-transfer",
  "warehouse-transfer-cancel",
  "product-create",
  "product-update",
  "customer-create",
  "customer-update",
  "customer-collect",
  "customer-payment",
  "supplier-create",
  "supplier-update",
  "supplier-payment",
  "supplier-collect",
  "supplier-adjustment",
  "employee-payment",
  "employee-salary",
  "employee-status",
  "expense-create",
  "expense-cancel",
  "expense-pay",
  "cash-bank-manual-transaction",
  "account-transfer",
  "account-create",
  "invoice-create",
  "invoice-update",
  "invoice-cancel",
  "invoice-delete",
  "invoice-collect",
  "invoice-status-change",
  "invoice-bulk-action",
  "invoice-create-from-sale",
  "e-invoice-create",
  "invoice-e-document-action",
  "notification-read",
  "metadata-toggle",
  // ─── Sipariş modülü ───────────────────────────────────────────────────────
  "order-status-update",
  "order-approve",
  "order-cancel",
  "order-archive",
  "order-restore",
  "order-bulk-status",
  "order-bulk-shipping",
  "order-import",
  // ─── Teklif modülü ────────────────────────────────────────────────────────
  "quote-cancel",
  "quote-convert",
  // ─── Metadata yöneticileri ────────────────────────────────────────────────
  "product-category-change",
  "expense-category-change",
  "customer-group-change",
] as const;

export type TenantMutationReason = (typeof TENANT_MUTATION_REASONS)[number];
